name: bigeq-authorize-dashboard-staging
region: nyc
services:
  - name: web
    dockerfile_path: Dockerfile
    github:
      branch: sprint-main
      deploy_on_push: true
      repo: kkeeling/bigeq-authorize-dashboard
    envs:
      - key: VITE_API_URL
        scope: RUN_TIME
        value: ${VITE_API_URL}
      - key: VITE_AUTH_TOKEN
        scope: RUN_TIME
        value: ${VITE_AUTH_TOKEN}
    http_port: 80
    instance_count: 1
    instance_size_slug: basic-xxs
    health_check:
      http_path: /
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
