name: authorize-dashboard-staging
region: nyc

services:
  - name: web
    image:
      registry_type: DOCR
      repository: bigeq-authorize-dashboard
      tag: staging
    envs:
      - key: VITE_API_URL
        scope: RUN_TIME
        value: ${VITE_API_URL}
      - key: VITE_AUTH_TOKEN
        scope: RUN_TIME
        value: ${VITE_AUTH_TOKEN}
    http_port: 80
    instance_count: 1
    instance_size_slug: basic-xxs
    health_check:
      http_path: /
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
