name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Login to DigitalOcean Container Registry
        run: doctl registry login --access-token ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t bigeq-authorize-dashboard:production .
          docker tag bigeq-authorize-dashboard:production registry.digitalocean.com/bigeq-authorize-dashboard:production
          docker push registry.digitalocean.com/bigeq-authorize-dashboard:production

      - name: Deploy to Digital Ocean App Platform
        run: |
          APP_ID=$(doctl apps list --format ID --no-header --output json | jq -r '.[] | select(.spec.name == "authorize-dashboard-prod") | .id')
          if [ -z "$APP_ID" ]; then
            echo "Creating new app..."
            doctl apps create --spec .do/app.prod.yaml
          else
            echo "Updating existing app..."
            doctl apps update $APP_ID --spec .do/app.prod.yaml
          fi
