name: Deploy to Staging

on:
  push:
    branches:
      - sprint-main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Build
        run: bun run build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_AUTH_TOKEN: ${{ secrets.VITE_AUTH_TOKEN }}

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Deploy to Digital Ocean App Platform
        run: |
          # Get existing app ID or create new app
          APP_ID=$(doctl apps list --format ID --no-header --output json | jq -r '.[] | select(.spec.name == "authorize-dashboard-staging") | .id')
          if [ -z "$APP_ID" ]; then
            echo "Creating new app..."
            doctl apps create --spec .do/app.yaml
          else
            echo "Updating existing app..."
            doctl apps update $APP_ID --spec .do/app.yaml
          fi
