name: Deploy to Staging

on:
  push:
    branches:
      - sprint-main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Login to DigitalOcean Container Registry
        run: |
          doctl registry login --access-token ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          doctl registry login --expiry-seconds 1200

      - name: Build and Push Docker Image
        run: |
          docker build -t registry.digitalocean.com/bigeq-authorize-dashboard/bigeq-authorize-dashboard:staging .
          docker push registry.digitalocean.com/bigeq-authorize-dashboard/bigeq-authorize-dashboard:staging

      - name: Deploy to Digital Ocean App Platform
        run: |
          APP_ID=$(doctl apps list --format ID --no-header --output json | jq -r '.[] | select(.spec.name == "authorize-dashboard-staging") | .id')
          if [ -z "$APP_ID" ]; then
            echo "Creating new app..."
            doctl apps create --spec .do/app.yaml
          else
            echo "Updating existing app..."
            doctl apps update $APP_ID --spec .do/app.yaml
          fi
